#!/bin/bash

RED='\033[0;31m'
NC='\033[0m'

if [ $# -eq 0 ]; then
  echo -e "${RED}need to supply name!"
  echo -e "usage: makescript <filename>${NC}"
  exit -1
fi

if [ -e $1 ]; then
  echo -e "${RED}file or directory ${1} allready exists!${NC}"
  exit -1
fi

echo "#!/bin/bash" >>$1
chmod 755 $1

nvim $1
